### ISSUE TITLE
errors on Rails 3.0.3 with postgres

### ISSUE THREAD

**Issue by ludicast** [mdarby/restful_acl#9]
I'm getting the error 

undefined method `visit_ActiveSupport_SafeBuffer' for #Arel::Visitors::PostgreSQL:0x29a1b98

whenever the allowed? helper method is called.  Not sure if it's just me though, but it worked fine on 3.0.0.

**Comment by mdarby** [comment]
It seems that something in the 3.0.3 release broke RESTful_ACL. Looking into it.

**Comment by mdarby** [comment]
I just pushed 3.1.4 which solves this issue.

**Comment by ludicast** [comment]
Heya-

Thanks for the push.  Still getting error though (both from 3.1.4 and bundling from github).  The relevant parts of my stack trace are below.

arel (2.0.4) lib/arel/visitors/visitor.rb:15:in `visit'
arel (2.0.4) lib/arel/visitors/to_sql.rb:235:in`visit_Arel_Nodes_Equality'
arel (2.0.4) lib/arel/visitors/visitor.rb:15:in `visit'
arel (2.0.4) lib/arel/visitors/to_sql.rb:109:in`visit_Arel_Nodes_Grouping'
arel (2.0.4) lib/arel/visitors/visitor.rb:15:in `visit'
arel (2.0.4) lib/arel/visitors/to_sql.rb:89:in`block in visit_Arel_Nodes_SelectCore'
arel (2.0.4) lib/arel/visitors/to_sql.rb:89:in `map'
arel (2.0.4) lib/arel/visitors/to_sql.rb:89:in`visit_Arel_Nodes_SelectCore'
arel (2.0.4) lib/arel/visitors/to_sql.rb:77:in `block in visit_Arel_Nodes_SelectStatement'
arel (2.0.4) lib/arel/visitors/to_sql.rb:77:in`map'
arel (2.0.4) lib/arel/visitors/to_sql.rb:77:in `visit_Arel_Nodes_SelectStatement'
arel (2.0.4) lib/arel/visitors/postgresql.rb:24:in`visit_Arel_Nodes_SelectStatement'
arel (2.0.4) lib/arel/visitors/visitor.rb:15:in `visit'
arel (2.0.4) lib/arel/visitors/visitor.rb:5:in`accept'
arel (2.0.4) lib/arel/visitors/to_sql.rb:19:in `block in accept'
activerecord (3.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:110:in`with_connection'
arel (2.0.4) lib/arel/visitors/to_sql.rb:17:in `accept'
arel (2.0.4) lib/arel/tree_manager.rb:19:in`to_sql'
activerecord (3.0.3) lib/active_record/relation.rb:64:in `to_a'
activerecord (3.0.3) lib/active_record/relation/finder_methods.rb:333:in`find_first'
activerecord (3.0.3) lib/active_record/relation/finder_methods.rb:122:in `first'
activerecord (3.0.3) lib/active_record/relation/finder_methods.rb:291:in`find_one'
activerecord (3.0.3) lib/active_record/relation/finder_methods.rb:281:in `find_with_ids'
activerecord (3.0.3) lib/active_record/relation/finder_methods.rb:107:in`find'
activerecord (3.0.3) lib/active_record/base.rb:439:in `find'
/Users/natekidwell/.bundler/ruby/1.9.1/restful_acl-007a94b09a18/lib/restful_acl/base.rb:13:in`load_actors_from_id'
/Users/natekidwell/.bundler/ruby/1.9.1/restful_acl-007a94b09a18/lib/restful_acl/base.rb:9:in `initialize'
/Users/natekidwell/.bundler/ruby/1.9.1/restful_acl-007a94b09a18/lib/restful_acl/helper.rb:6:in`new'
/Users/natekidwell/.bundler/ruby/1.9.1/restful_acl-007a94b09a18/lib/restful_acl/helper.rb:6:in `allowed?'

**Comment by mdarby** [comment]
Can you try rebundling from GH again now? I just updated base.rb.

**Comment by ludicast** [comment]
That did it!  Thanks as always for restful_acl.

**Comment by mdarby** [comment]
Awesome. I'll push 3.1.5 here in a minute. Thanks for bearing with us :)
